### ISSUE TITLE
Broken link on "Adding an SSH key page"

### ISSUE THREAD

**Issue by DanHeidinga** [ibm-cloud-docs/ssh-keys#3]
The link under "Navigating to devices" from [1] goes to a "Sorry this content isn't available" page.

Sentence on the page:
> Navigate to your console's device menu. For more information, see 'Navigating to devices."

Broken Link:
https://cloud.ibm.com/docs/infrastructure/ssh-keys?topic=virtual-servers-navigating-devices

[1] https://cloud.ibm.com/docs/ssh-keys?topic=ssh-keys-adding-an-ssh-key

**Comment by gudrun-wolfgram** [comment]
Thanks for letting us know. A fix has been implemented for the broken link.
